### ISSUE TITLE
Cannot resolve module 'webpack-hot-middleware/client'

### ISSUE THREAD

**Issue by kevinsimper** [egoist/tooling#2]
I just installed tooling and i get this error, probrably just missing to install it, but it does not say that in the README

```
ERROR in multi main
Module not found: Error: Cannot resolve module 'webpack-hot-middleware/client' in /Users/zzz/Projects/xxx
 @ multi main
```

**Comment by egoist** [comment]
Thanks for feedback, it should require `webpack-hot-middleware/client` from `tooling`'s path but it didn't, fixed in the latest release.
