### ISSUE TITLE
how to deploy the application to Heroku?

### ISSUE THREAD

**Issue by henry40408** [egoist/tooling#22]
refer to #21, `tooling` is not recommended to be included in `devDependencies`, so what is the recommended way to deploy the application built by `tooling` to Heroku?

**Comment by egoist** [comment]
The bundled results are just static files, what do you mean by `deploy them to heroku`?

**Comment by henry40408** [comment]
Currently, I need to do the following steps to deploy my application to
Heroku:

1. compile bundle.js on my laptop
2. stage them onto the repository
3. git push to Heroku

However, I soon find that my build directory messed up by expired versions
of bundle.js. Is there any better ways to avoid the situation?

If bundle.js needed to be compiled on Heroku, I would have to add tooling
as devDependencies and register postinstall hook in package.json

BTW, I use harp.js as my production web server.

EGOISTIAN <notifications@github.com> 於 2016年3月12日 星期六寫道：

> The bundled results are just static files, what do you mean by deploy
> them to heroku?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/egoist/tooling/issues/22#issuecomment-195679366>.
>


-- 
吳恒毅

Tel: 0917-131-831
email: henry40408@gmail.com

**Comment by egoist** [comment]
Feel free to install tooling as devDep on heroku, it's only not recommended to install tooling on your local machine, because it's slow. Or is there a way to install tooling globally on heroku? I dunno that.

If you feel messy about your `build` dir, just do add `rm -rf build` into your npm script before build.
