### ISSUE TITLE
Adding example projects using tooling

### ISSUE THREAD

**Issue by egoist** [egoist/tooling#25]

**Comment by hanaarena** [comment]
When I follow the [youtube video](https://www.youtube.com/watch?v=_odq2Sc1Sko),it alway show below:

<img width="797" alt="2016-04-05 12 03 07" src="https://cloud.githubusercontent.com/assets/2683068/14271006/709a80ca-fb26-11e5-914d-94f5d1aec2ec.png">

have no idea..(￣ー￣)

**Comment by egoist** [comment]
@hanaarena Sorry, this is some updates, you should use `-u vue` aka `--use vue` to resolve vue files.

**Comment by hanaarena** [comment]
阿 好了 !(๑•̀ㅂ•́)و✧

**Comment by egoist** [comment]
Example project is done here. https://github.com/egoist/tiktok
